databases:
- 'dbname=my_db user=my_user password= host=localhost'

tilejson_spec: >
  {tilejson: '2.1.0',
  name: 'utilery',
  description: 'A lite vector tile server',
  scheme: 'xyz',
  format: 'pbf',
  tiles: [
    'http://vector.myserver.org/all/{z}/{x}/{y}.pbf'
  ]}

builtin_plugins:
- utilery.plugins.builtins.CORS
plugins: []
debug: True
srid: 3857
scale: 1
buffer: 0
clip: False
CORS: '*'
log_level: 'info'