# TODO: remove this file later. Presently a workaround for building docs in readthedocs for python 3.5

name: py35
dependencies:
- python=3.5.1=0
- pip=8.1.2=py35_0
- PyYAML
- psycopg2
- ujson
- pip:
  - protobuf>=3.0.0b4
  - mapbox-vector-tile
  - mercantile
  - aiopg
  - aiohttp
  - aiohttp_cors
  - cchardet