site_name: aiovectortiler
theme: readthedocs
repo_url: https://github.com/shongololo/aiovectortiler.git
site_description: Asynchronous micro vector tiler serving data from PostGIS.
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuration]
- [api.md, Endpoints]
- [plugins.md, Plugins]
