layers:
- name: "nyc_blocks_data"
  buffer: 0
  clip: false
  SRID: 3857
  queries:
  - minzoom: 12
    maxzoom: 22
    sql: |
      SELECT
        "id",
        ST_Transform(geom, 3857) as way
      FROM
        nyc_blocks_data