log_level: 'info'
databases:
  default: 'dbname=my_db user=my_user password= host=localhost'
default_recipe: 'example_recipe'
SRID: 3857  # optional global parameter
scale: 1  # optional global parameter
buffer: 0  # optional global parameter
clip: False  # optional global parameter
CORS: '*'

builtin_plugins: []
plugins: []

tileJSON_spec: >
  {"tilejson": "2.1.0",
  "name": "aiovectortiler",
  "description": "Asynchronous micro vector tile server for PostGIS.",
  "scheme": "xyz",
  "format": "pbf",
  "tiles": [
    "https://vector_tile_demo_host.com/all/{z}/{x}/{y}.pbf"
  ]}
